language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - EXTRAS=all
  - EXTRAS=dev


matrix:
  include:
    - os: windows
      language: sh
      python: "3.6"
      env:
        - EXTRAS=all
        - PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:/c/tools/miniconda3/Library/bin:$PATH"
      before_install:
        - choco install miniconda3
        - conda create --yes -n test python=3.6
        - source activate test
        - conda --version ; python --version ; pip --version

    - os: windows
      language: sh
      python: "3.7"
      env:
        - EXTRAS=all
        - PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:/c/tools/miniconda3/Library/bin:$PATH"
      before_install:
        - choco install miniconda3
        - conda create --yes -n test python=3.7
        - source activate test
        - conda --version ; python --version ; pip --version

    - os: windows
      language: sh
      python: "3.8"
      env:
        - EXTRAS=all
        - PATH="/c/tools/miniconda3/:/c/tools/miniconda3/Scripts:/c/tools/miniconda3/Library/bin:$PATH"
      before_install:
        - choco install miniconda3
        - conda create --yes -n test python=3.8
        - source activate test
        - conda --version ; python --version ; pip --version

# command to install dependencies
install:
  - if [[ $EXTRAS == 'all' ]]; then pip install sphinx; fi
  - if [[ $EXTRAS == 'dev' ]]; then pip install -r requirements/dev.pip; fi
  - pip install -r requirements/test.pip
  - pip install -e .[$EXTRAS]

# command to run tests
script:
  - coverage run --source=xlref setup.py test

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.7' && $EXTRAS == 'all' && $TRAVIS_OS_NAME == 'linux' ]]; then coveralls; fi